ARG version
FROM almalinux:${version:-8}
RUN cat /etc/*release
ARG course=docker
ARG duration=10
ENV trainer=shiva
RUN echo "course:${course}, duration:${duration}, trainer:${trainer}"
CMD [ "sleep","100" ]